# Generated by Django 4.1.2 on 2022-10-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='phonenumber',
            field=models.CharField(max_length=255),
        ),
    ]
